[project]
name = "nucleo-cognitivo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Aelton0", email = "aeltonsoaresdemenezes@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
nucleo-cognitivo = "nucleo_cognitivo:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
